<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>LIS2.ProtocolTester</AssemblyName>
    <RootNamespace>LIS2.ProtocolTester</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <ProjectReference Include="..\..\src\LIS2.Core\LIS2.Core.csproj" />
  </ItemGroup>
</Project>
