namespace LIS2.App;

internal static partial class HelpLocalization
{
    private static readonly IReadOnlyDictionary<string, string> Russian =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["LIS2 Control Center Help"] = "Справка LIS2 Control Center",
            ["Help & reference"] = "Справка и справочник",
            ["Instructions, configuration reference and display-variable examples."] = "Инструкции, справочник по настройке и примеры переменных дисплея.",

            ["The Dashboard is the operational overview. It shows the current 20x2 VFD frame, connection state, virtual-device state, recent log messages and direct fan-output controls."] = "Обзор — это основная рабочая сводка. Здесь показаны текущий кадр VFD 20x2, состояние подключения, состояние виртуального устройства, последние сообщения журнала и прямое управление выходами вентиляторов.",
            ["VFD Preview"] = "Предпросмотр VFD",
            ["Shows the two normalized 20-character lines currently held by the application. Long page text may scroll at runtime; the preview shows the current rendered frame."] = "Показывает две нормализованные строки по 20 символов, которые приложение выводит в данный момент. Длинный текст страницы может прокручиваться; предпросмотр показывает текущий отрисованный кадр.",
            ["Fan Outputs"] = "Выходы вентиляторов",
            ["The four sliders apply manual outputs through the same safety limits configured on Fan Control. Minimum and maximum limits still apply."] = "Четыре ползунка задают ручные выходные значения с теми же ограничениями безопасности, что и в управлении вентиляторами. Ограничения минимума и максимума продолжают действовать.",
            ["Quick links and status"] = "Быстрые ссылки и состояние",
            ["Quick links open Display or Fan Control. With Virtual transport selected, the status card mirrors the emulated LIS2 state."] = "Быстрые ссылки открывают разделы дисплея или управления вентиляторами. При виртуальном транспорте карточка состояния отражает эмулированное состояние LIS2.",

            ["Display contains direct low-level controls for the physical or virtual LIS2. They bypass page scheduling and are intended for testing and one-off output."] = "Раздел дисплея содержит прямые низкоуровневые элементы управления физическим или виртуальным LIS2. Они обходят планировщик страниц и предназначены для тестов и разового вывода.",
            ["Direct line output"] = "Прямой вывод строк",
            ["Line 1 and Line 2 are each limited to 20 display characters. Render both lines writes a complete frame. Clear sends the LIS2 clear/reset command."] = "Строки 1 и 2 ограничены 20 символами каждая. «Вывести обе строки» записывает полный кадр. «Очистить» отправляет команду очистки/сброса LIS2.",
            ["Brightness"] = "Яркость",
            ["Supported levels are 100%, 75%, 50% and 25%. Brightness-off remains intentionally unsupported until verified on real hardware."] = "Поддерживаются уровни 100 %, 75 %, 50 % и 25 %. Полное выключение яркости намеренно не поддерживается до проверки на реальном оборудовании.",
            ["Custom characters / CG Builder"] = "Пользовательские символы / CG Builder",
            ["The LIS2 exposes eight programmable 5x8 character slots. Use these variables in page templates:"] = "LIS2 предоставляет восемь программируемых слотов символов 5x8. Используйте эти переменные в шаблонах страниц:",
            ["Named glyphs use the saved glyph name after normalization."] = "Именованные глифы используют сохранённое имя после нормализации.",
            ["Character ROM"] = "ПЗУ символов",
            ["Special-character and raw-ROM tools are validation tools for the known uPD16314 mapping. Physical behavior still needs verification on the real LIS2."] = "Инструменты специальных символов и сырых байтов ПЗУ предназначены для проверки известного отображения uPD16314. Физическое поведение всё ещё нужно подтвердить на настоящем LIS2.",

            ["Pages define the rotating VFD presentation. Each enabled page has two templates, duration, optional visibility rules and an independent overflow mode per line."] = "Страницы определяют циклическое отображение VFD. Каждая включённая страница имеет два шаблона, длительность, необязательные правила видимости и отдельный режим переполнения для каждой строки.",
            ["Configuration"] = "Конфигурация",
            ["Name: descriptive page name."] = "Имя: описательное имя страницы.",
            ["Enabled: disabled pages are excluded from rotation."] = "Включено: отключённые страницы исключаются из ротации.",
            ["Duration: page lifetime in seconds; minimum 1 second."] = "Длительность: время показа страницы в секундах; минимум 1 секунда.",
            ["Line 1 / Line 2: text templates with {Variable} placeholders."] = "Строка 1 / Строка 2: текстовые шаблоны с заполнителями {Variable}.",
            ["Overflow: PingPong, Marquee or Truncate per line."] = "Переполнение: PingPong, Marquee или Truncate для каждой строки.",
            ["Scroll step: 50–5000 ms in the editor."] = "Шаг прокрутки: 50–5000 мс в редакторе.",
            ["Edge pause: 0–10000 ms in the editor."] = "Пауза у края: 0–10000 мс в редакторе.",
            ["Visible when: optional condition controlling whether the page is eligible."] = "Видима когда: необязательное условие, определяющее возможность показа страницы.",
            ["Template formatting"] = "Форматирование шаблонов",
            ["Operations can be chained left to right. fallback handles missing, null, unknown or unavailable values. number supports 0–6 decimals. bytes uses B/KB/MB/GB/TB/PB."] = "Операции можно объединять слева направо. fallback обрабатывает отсутствующие значения, null, unknown и unavailable. number поддерживает 0–6 знаков после запятой. bytes использует B/KB/MB/GB/TB/PB.",
            ["Visibility expressions"] = "Выражения видимости",
            ["Supported operators are =, !=, >, >=, < and <=. Equality is case-insensitive text comparison; ordering operators require numeric values."] = "Поддерживаются операторы =, !=, >, >=, < и <=. Равенство сравнивает текст без учёта регистра; операторы порядка требуют числовых значений.",
            ["Clock variables"] = "Переменные часов",
            ["Current local time, HH:mm:ss."] = "Текущее локальное время, HH:mm:ss.",
            ["Current local date, dd.MM.yyyy."] = "Текущая локальная дата, dd.MM.yyyy.",
            ["Current local weekday."] = "Текущий локальный день недели.",
            ["Currently available variables"] = "Доступные сейчас переменные",
            ["This list comes from the current runtime snapshot. Home Assistant itself is intentionally not expanded into thousands of help entries; use the dedicated HA help with examples and the HA browser for exact entity/attribute names."] = "Этот список получен из текущего снимка состояния. Home Assistant намеренно не разворачивается в тысячи пунктов справки; используйте отдельную справку HA с примерами и браузер HA для точных имён сущностей и атрибутов.",
            ["No matching runtime variables are currently available."] = "Подходящие переменные времени выполнения сейчас отсутствуют.",

            ["Winamp telemetry comes from the native x86 gen_lis2.dll plug-in over the LIS2ControlCenter.Winamp named pipe."] = "Телеметрия Winamp поступает из нативного x86-плагина gen_lis2.dll через именованный канал LIS2ControlCenter.Winamp.",
            ["All Winamp variables"] = "Все переменные Winamp",
            ["Unknown, Stopped, Paused or Playing."] = "Unknown, Stopped, Paused или Playing.",
            ["Current artist."] = "Текущий исполнитель.",
            ["Current title."] = "Текущее название.",
            ["Current album."] = "Текущий альбом.",
            ["Current playlist position."] = "Текущая позиция в списке воспроизведения.",
            ["Number of playlist entries."] = "Количество элементов списка воспроизведения.",
            ["Elapsed time as mm:ss."] = "Прошедшее время в формате mm:ss.",
            ["Track duration as mm:ss."] = "Длительность трека в формате mm:ss.",
            ["Bitrate in kbit/s."] = "Битрейт в кбит/с.",
            ["Sample rate in Hz."] = "Частота дискретизации в Гц.",
            ["Left VU level."] = "Уровень левого VU.",
            ["Right VU level."] = "Уровень правого VU.",
            ["Preformatted 20-character stereo VU line."] = "Предварительно отформатированная 20-символьная строка стерео VU.",
            ["20-band ASCII spectrum."] = "20-полосный ASCII-спектр.",
            ["Raw spectrum array."] = "Необработанный массив спектра.",
            ["Peak spectrum value."] = "Пиковое значение спектра.",
            ["20-band spectrum using the eight custom VFD glyph levels."] = "20-полосный спектр с восемью уровнями пользовательских глифов VFD.",
            ["True while snapshots are fresh."] = "True, пока снимки состояния актуальны.",
            ["Age of the last snapshot."] = "Возраст последнего снимка.",
            ["Typical page"] = "Типичная страница",

            ["Events are temporary priority overlays. While active they override normal page rotation; after expiry the scheduler returns to the normal page."] = "События — это временные приоритетные наложения. Пока они активны, обычная ротация страниц заменяется; после истечения времени планировщик возвращается к обычной странице.",
            ["Line 1 / Line 2: event text."] = "Строка 1 / Строка 2: текст события.",
            ["Priority: higher priority events win."] = "Приоритет: событие с более высоким приоритетом имеет преимущество.",
            ["Duration: 1–3600 seconds."] = "Длительность: 1–3600 секунд.",
            ["Expired events are removed automatically."] = "Истёкшие события удаляются автоматически.",

            ["Hardware uses LibreHardwareMonitor and publishes CPU, GPU, memory, motherboard, storage, network and controller sensor values."] = "Раздел оборудования использует LibreHardwareMonitor и публикует значения датчиков CPU, GPU, памяти, материнской платы, накопителей, сети и контроллеров.",
            ["Variable pattern"] = "Шаблон переменной",
            ["Hardware and sensor names are normalized: non-alphanumeric characters become underscores. Exact variable names depend on the computer."] = "Имена оборудования и датчиков нормализуются: не буквенно-цифровые символы заменяются подчёркиваниями. Точные имена переменных зависят от компьютера.",
            ["Units"] = "Единицы",
            ["Temperature → C"] = "Температура → C",
            ["Load → %"] = "Нагрузка → %",
            ["Fan → RPM"] = "Вентилятор → RPM",
            ["Clock → MHz"] = "Частота → MHz",
            ["Voltage → V"] = "Напряжение → V",
            ["Power → W"] = "Мощность → W",
            ["Data → GB"] = "Данные → GB",
            ["SmallData → MB"] = "Малые данные → MB",
            ["Throughput → B/s"] = "Пропускная способность → B/s",
            ["Currently detected hardware variables"] = "Обнаруженные сейчас аппаратные переменные",

            ["Fan Control configures the four LIS2 fan channels. Software safety limits are applied before output is sent."] = "Управление вентиляторами настраивает четыре канала LIS2. Перед отправкой выходного значения применяются программные ограничения безопасности.",
            ["Modes"] = "Режимы",
            ["Fixed: configured fixed output."] = "Фиксированный: настроенное постоянное выходное значение.",
            ["Curve: interpolates between temperature/output points."] = "Кривая: интерполирует между точками температура/выход.",
            ["Follow: converts the selected numeric sensor value directly to a percentage."] = "Следование: напрямую преобразует выбранное числовое значение датчика в процент.",
            ["External: uses an externally supplied percentage."] = "Внешний: использует процент, поступающий извне.",
            ["Off: outputs 0% only when Allow stop is enabled; otherwise minimum output is used."] = "Выключено: выдаёт 0 % только при разрешённой остановке; иначе используется минимальный выход.",
            ["Safety"] = "Безопасность",
            ["Minimum: lower non-zero limit."] = "Минимум: нижняя ненулевая граница.",
            ["Maximum: upper limit."] = "Максимум: верхняя граница.",
            ["Fail-safe: used when a required sensor is missing or invalid."] = "Аварийное значение: используется, если требуемый датчик отсутствует или недействителен.",
            ["Hysteresis: suppresses small curve changes."] = "Гистерезис: подавляет небольшие изменения по кривой.",
            ["Allow stop: permits 0% and requires explicit confirmation."] = "Разрешить остановку: допускает 0 % и требует явного подтверждения.",
            ["Safe minimum speed and reliable restart at 0% are physical properties and must be verified with the actual fan hardware."] = "Безопасная минимальная скорость и надёжный перезапуск после 0 % являются физическими свойствами и должны быть проверены на реальных вентиляторах.",

            ["Settings controls transport, COM port, appearance/language and Windows startup."] = "Настройки управляют транспортом, COM-портом, оформлением/языком и автозапуском Windows.",
            ["Transport"] = "Транспорт",
            ["Virtual: software-only emulator and recommended mode without hardware."] = "Виртуальный: программный эмулятор и рекомендуемый режим без оборудования.",
            ["Serial: physical LIS2. A COM port is required."] = "Последовательный: физический LIS2. Требуется COM-порт.",
            ["Known serial parameters: 19200 baud, 8 data bits, no parity, one stop bit."] = "Известные параметры порта: 19200 бод, 8 бит данных, без чётности, один стоп-бит.",
            ["Appearance"] = "Оформление",
            ["Theme can follow Windows or use Light/Dark. Language can follow the system or use English, German, French, Turkish or Russian."] = "Тема может следовать Windows или использовать светлый/тёмный режим. Язык может следовать системе либо быть английским, немецким, французским, турецким или русским.",
            ["Startup / tray"] = "Автозапуск / область уведомлений",
            ["Autostart is per-user. Closing the main window normally keeps the application alive in the tray."] = "Автозапуск задаётся для текущего пользователя. Закрытие главного окна обычно оставляет приложение работающим в области уведомлений.",

            ["Diagnostics combines application state, source health, Virtual LIS2 state and decoded command history."] = "Диагностика объединяет состояние приложения, состояние источников, состояние виртуального LIS2 и историю декодированных команд.",
            ["Virtual LIS2"] = "Виртуальный LIS2",
            ["Shows both lines, brightness, four fan outputs, all eight glyphs, rejected-command count and the most recent protocol error."] = "Показывает обе строки, яркость, четыре выхода вентиляторов, все восемь глифов, число отклонённых команд и последнюю ошибку протокола.",
            ["Command history"] = "История команд",
            ["Shows up to the last 200 writes as hexadecimal bytes plus decoded command descriptions."] = "Показывает до 200 последних записей в виде шестнадцатеричных байтов и декодированных описаний команд.",
            ["Export"] = "Экспорт",
            ["Export diagnostic report saves the current snapshot for bug reports and hardware-validation sessions."] = "Экспорт диагностического отчёта сохраняет текущий снимок для сообщений об ошибках и сеансов проверки оборудования.",

            ["Home Assistant is the universal read-only integration layer. The app authenticates to the WebSocket API, loads the initial states and then receives live state_changed events."] = "Home Assistant — универсальный интеграционный слой только для чтения. Приложение аутентифицируется в WebSocket API, загружает начальные состояния и затем получает события state_changed в реальном времени.",
            ["Connection"] = "Подключение",
            ["URL: absolute http:// or https:// Home Assistant base URL."] = "URL: абсолютный базовый URL Home Assistant с http:// или https://.",
            ["Token: long-lived Home Assistant access token."] = "Токен: долгоживущий токен доступа Home Assistant.",
            ["Test connection: checks WebSocket greeting and authentication."] = "Проверить подключение: проверяет приветствие WebSocket и аутентификацию.",
            ["Save / reconnect: stores settings and restarts the HA source."] = "Сохранить / переподключить: сохраняет настройки и перезапускает источник HA.",
            ["Connection failures are retried automatically."] = "После ошибок подключения повтор выполняется автоматически.",
            ["The four basic variable forms"] = "Четыре основные формы переменных",
            ["Entity state. Example result: 21.7"] = "Состояние сущности. Пример результата: 21,7",
            ["unit_of_measurement. Example result: °C"] = "unit_of_measurement. Пример результата: °C",
            ["friendly_name. Example result: Living room temperature"] = "friendly_name. Пример результата: Температура в гостиной",
            ["Any attribute exposed by the entity. Example result: temperature"] = "Любой атрибут, предоставляемый сущностью. Пример результата: temperature",
            ["Attribute examples"] = "Примеры атрибутов",
            ["The exact attributes depend entirely on the Home Assistant integration. Select an entity in the HA browser to see every attribute currently exposed by that entity."] = "Точные атрибуты полностью зависят от интеграции Home Assistant. Выберите сущность в браузере HA, чтобы увидеть все атрибуты, которые она предоставляет сейчас.",
            ["Example: current media title, if the media_player exposes media_title."] = "Пример: текущий заголовок медиа, если media_player предоставляет media_title.",
            ["Example: current media artist, if available."] = "Пример: текущий исполнитель, если доступен.",
            ["Example: a custom/integration-specific disk attribute named free."] = "Пример: пользовательский или специфичный для интеграции атрибут диска с именем free.",
            ["Example: an attribute named temperature, if that weather entity exposes it."] = "Пример: атрибут temperature, если погодная сущность его предоставляет.",
            ["These are syntax examples, not a promise that every HA installation has those exact entities or attributes."] = "Это примеры синтаксиса, а не обещание, что в каждой установке HA есть именно такие сущности или атрибуты.",
            ["Aliases"] = "Псевдонимы",
            ["Assign an alias in the HA browser when an entity ID is long or unstable. The same state, Unit, FriendlyName and attribute namespace is then available below the alias."] = "Назначьте псевдоним в браузере HA, если ID сущности длинный или неудобный. То же состояние, Unit, FriendlyName и пространство имён атрибутов станут доступны и под псевдонимом.",
            ["Formatting examples"] = "Примеры форматирования",
            ["Formatting operations are the same as on every page variable: fallback, number, percent, bytes, prefix, suffix, upper and lower."] = "Операции форматирования одинаковы для всех переменных страниц: fallback, number, percent, bytes, prefix, suffix, upper и lower.",
            ["Visibility examples"] = "Примеры видимости",
            ["Use the Visibility Builder on Pages to select a live HA variable and operator instead of typing the expression manually."] = "Используйте конструктор видимости на странице «Страницы», чтобы выбрать живую переменную HA и оператор вместо ручного ввода выражения.",
            ["unknown / unavailable"] = "unknown / unavailable",
            ["The template renderer treats null, unknown and unavailable as unavailable. This is why fallback is especially useful for HA values."] = "Шаблонизатор считает null, unknown и unavailable недоступными значениями. Поэтому fallback особенно полезен для значений HA.",
            ["Arrays and objects"] = "Массивы и объекты",
            ["Some integrations expose structured attributes such as lists or objects. LIS2 Control Center exposes them as compact JSON."] = "Некоторые интеграции предоставляют структурированные атрибуты, например списки или объекты. LIS2 Control Center показывает их как компактный JSON.",
            ["Example result: [1,2,3]"] = "Пример результата: [1,2,3]",
            ["Example result: {\"temperature\":21,\"condition\":\"sunny\"}"] = "Пример результата: {\"temperature\":21,\"condition\":\"sunny\"}",
            ["For a 20x2 VFD, structured JSON is usually too large to display directly. Use the HA browser to inspect it; dedicated extraction/formatting should only be added for a concrete real-world use case."] = "Для VFD 20x2 структурированный JSON обычно слишком велик для прямого отображения. Просматривайте его в браузере HA; специальное извлечение или форматирование следует добавлять только для конкретного практического сценария.",
            ["How to find the exact variable"] = "Как найти точную переменную",
            ["Open Home Assistant in LIS2 Control Center."] = "Откройте Home Assistant в LIS2 Control Center.",
            ["Search by entity ID, friendly name or alias."] = "Ищите по ID сущности, отображаемому имени или псевдониму.",
            ["Select the entity."] = "Выберите сущность.",
            ["Use the attribute list to inspect every available attribute."] = "Используйте список атрибутов, чтобы просмотреть все доступные атрибуты.",
            ["Use Copy key or Create display page to avoid typing long keys manually."] = "Используйте «Копировать ключ» или «Создать страницу дисплея», чтобы не вводить длинные ключи вручную.",
            ["The help deliberately does not list every entity from your real Home Assistant instance. Large installations can have thousands of entities; the HA browser is the authoritative live catalogue."] = "Справка намеренно не перечисляет все сущности вашей реальной установки Home Assistant. В крупных системах их могут быть тысячи; браузер HA является актуальным живым каталогом."
        };
}
