namespace LIS2.App;

internal static partial class HelpLocalization
{
    private static readonly IReadOnlyDictionary<string, string> French =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["LIS2 Control Center Help"] = "Aide LIS2 Control Center",
            ["Help & reference"] = "Aide et référence",
            ["Help for this page"] = "Aide pour cette page",
            ["Instructions, configuration reference and display-variable examples."] = "Instructions, référence de configuration et exemples de variables d’affichage.",

            ["The Dashboard is the operational overview. It shows the current 20x2 VFD frame, connection state, virtual-device state, recent log messages and direct fan-output controls."] = "Le tableau de bord est la vue d’ensemble opérationnelle. Il affiche la trame VFD 20x2 actuelle, l’état de connexion, l’état du périphérique virtuel, les derniers messages du journal et les commandes directes des ventilateurs.",
            ["VFD Preview"] = "Aperçu VFD",
            ["Shows the two normalized 20-character lines currently held by the application. Long page text may scroll at runtime; the preview shows the current rendered frame."] = "Affiche les deux lignes normalisées de 20 caractères actuellement produites par l’application. Les textes longs peuvent défiler à l’exécution ; l’aperçu montre la trame rendue à cet instant.",
            ["Fan Outputs"] = "Sorties ventilateurs",
            ["The four sliders apply manual outputs through the same safety limits configured on Fan Control. Minimum and maximum limits still apply."] = "Les quatre curseurs appliquent des sorties manuelles en respectant les mêmes limites de sécurité que dans le contrôle des ventilateurs. Les limites minimum et maximum restent actives.",
            ["Quick links and status"] = "Accès rapides et état",
            ["Quick links open Display or Fan Control. With Virtual transport selected, the status card mirrors the emulated LIS2 state."] = "Les accès rapides ouvrent l’affichage ou le contrôle des ventilateurs. Avec le transport virtuel, la carte d’état reflète l’état LIS2 émulé.",

            ["Display contains direct low-level controls for the physical or virtual LIS2. They bypass page scheduling and are intended for testing and one-off output."] = "Affichage contient des commandes bas niveau directes pour le LIS2 physique ou virtuel. Elles contournent la rotation des pages et servent aux tests ou aux sorties ponctuelles.",
            ["Direct line output"] = "Sortie directe des lignes",
            ["Line 1 and Line 2 are each limited to 20 display characters. Render both lines writes a complete frame. Clear sends the LIS2 clear/reset command."] = "Les lignes 1 et 2 sont chacune limitées à 20 caractères. « Afficher les deux lignes » écrit une trame complète. « Effacer » envoie la commande LIS2 d’effacement/réinitialisation.",
            ["Brightness"] = "Luminosité",
            ["Supported levels are 100%, 75%, 50% and 25%. Brightness-off remains intentionally unsupported until verified on real hardware."] = "Les niveaux pris en charge sont 100 %, 75 %, 50 % et 25 %. L’extinction de la luminosité reste volontairement non prise en charge tant qu’elle n’a pas été vérifiée sur le matériel réel.",
            ["Custom characters / CG Builder"] = "Caractères personnalisés / CG Builder",
            ["The LIS2 exposes eight programmable 5x8 character slots. Use these variables in page templates:"] = "Le LIS2 fournit huit emplacements de caractères programmables 5x8. Utilisez ces variables dans les modèles de page :",
            ["Named glyphs use the saved glyph name after normalization."] = "Les glyphes nommés utilisent le nom enregistré après normalisation.",
            ["Character ROM"] = "ROM de caractères",
            ["Special-character and raw-ROM tools are validation tools for the known uPD16314 mapping. Physical behavior still needs verification on the real LIS2."] = "Les outils de caractères spéciaux et de ROM brute servent à valider le mappage uPD16314 connu. Le comportement physique doit encore être vérifié sur le vrai LIS2.",

            ["Pages define the rotating VFD presentation. Each enabled page has two templates, duration, optional visibility rules and an independent overflow mode per line."] = "Les pages définissent l’affichage VFD en rotation. Chaque page activée possède deux modèles, une durée, des règles de visibilité facultatives et un mode de débordement indépendant par ligne.",
            ["Configuration"] = "Configuration",
            ["Name: descriptive page name."] = "Nom : nom descriptif de la page.",
            ["Enabled: disabled pages are excluded from rotation."] = "Activée : les pages désactivées sont exclues de la rotation.",
            ["Duration: page lifetime in seconds; minimum 1 second."] = "Durée : durée d’affichage de la page en secondes ; minimum 1 seconde.",
            ["Line 1 / Line 2: text templates with {Variable} placeholders."] = "Ligne 1 / Ligne 2 : modèles de texte avec des espaces réservés {Variable}.",
            ["Overflow: PingPong, Marquee or Truncate per line."] = "Débordement : PingPong, Défilement ou Tronquer pour chaque ligne.",
            ["Scroll step: 50–5000 ms in the editor."] = "Pas de défilement : 50–5000 ms dans l’éditeur.",
            ["Edge pause: 0–10000 ms in the editor."] = "Pause au bord : 0–10000 ms dans l’éditeur.",
            ["Visible when: optional condition controlling whether the page is eligible."] = "Visible si : condition facultative déterminant si la page peut être affichée.",
            ["Template formatting"] = "Formatage des modèles",
            ["Operations can be chained left to right. fallback handles missing, null, unknown or unavailable values. number supports 0–6 decimals. bytes uses B/KB/MB/GB/TB/PB."] = "Les opérations peuvent être enchaînées de gauche à droite. fallback gère les valeurs absentes, null, unknown ou unavailable. number accepte 0 à 6 décimales. bytes utilise B/KB/MB/GB/TB/PB.",
            ["Visibility expressions"] = "Expressions de visibilité",
            ["Supported operators are =, !=, >, >=, < and <=. Equality is case-insensitive text comparison; ordering operators require numeric values."] = "Les opérateurs pris en charge sont =, !=, >, >=, < et <=. L’égalité compare du texte sans tenir compte de la casse ; les opérateurs d’ordre exigent des valeurs numériques.",
            ["Clock variables"] = "Variables d’horloge",
            ["Current local time, HH:mm:ss."] = "Heure locale actuelle, HH:mm:ss.",
            ["Current local date, dd.MM.yyyy."] = "Date locale actuelle, dd.MM.yyyy.",
            ["Current local weekday."] = "Jour de la semaine local actuel.",
            ["Currently available variables"] = "Variables actuellement disponibles",
            ["This list comes from the current runtime snapshot. Home Assistant itself is intentionally not expanded into thousands of help entries; use the dedicated HA help with examples and the HA browser for exact entity/attribute names."] = "Cette liste provient de l’instantané d’exécution actuel. Home Assistant n’est volontairement pas développé en milliers d’entrées d’aide ; utilisez l’aide HA dédiée et le navigateur HA pour obtenir les noms exacts des entités et attributs.",
            ["No matching runtime variables are currently available."] = "Aucune variable d’exécution correspondante n’est actuellement disponible.",

            ["Winamp telemetry comes from the native x86 gen_lis2.dll plug-in over the LIS2ControlCenter.Winamp named pipe."] = "La télémétrie Winamp provient du plug-in natif x86 gen_lis2.dll via le tube nommé LIS2ControlCenter.Winamp.",
            ["Windows Media Player"] = "Windows Media Player",
            ["Windows Media Player on Windows 11 is read directly from the Windows global media session (GSMTC). No player plug-in is required."] = "Windows Media Player sous Windows 11 est lu directement via la session média globale de Windows (GSMTC). Aucun plug-in du lecteur n’est requis.",
            ["All Windows Media variables"] = "Toutes les variables Windows Media",
            ["Unknown, Closed, Opened, Changing, Stopped, Paused or Playing."] = "Unknown, Closed, Opened, Changing, Stopped, Paused ou Playing.",
            ["Current album artist."] = "Artiste de l’album actuel.",
            ["Total tracks reported for the current album."] = "Nombre total de pistes signalé pour l’album actuel.",
            ["Playback rate reported by Windows."] = "Vitesse de lecture signalée par Windows.",
            ["Source application user model ID."] = "Identifiant du modèle utilisateur de l’application source.",
            ["True while the Windows Media Player session is available."] = "True tant que la session Windows Media Player est disponible.",
            ["Typical Windows Media page"] = "Page Windows Media typique",
            ["All Winamp variables"] = "Toutes les variables Winamp",
            ["Unknown, Stopped, Paused or Playing."] = "Unknown, Stopped, Paused ou Playing.",
            ["Current artist."] = "Artiste actuel.",
            ["Current title."] = "Titre actuel.",
            ["Current album."] = "Album actuel.",
            ["Current playlist position."] = "Position actuelle dans la liste de lecture.",
            ["Number of playlist entries."] = "Nombre d’entrées dans la liste de lecture.",
            ["Elapsed time as mm:ss."] = "Temps écoulé au format mm:ss.",
            ["Track duration as mm:ss."] = "Durée du titre au format mm:ss.",
            ["Bitrate in kbit/s."] = "Débit en kbit/s.",
            ["Sample rate in Hz."] = "Fréquence d’échantillonnage en Hz.",
            ["Left VU level."] = "Niveau VU gauche.",
            ["Right VU level."] = "Niveau VU droit.",
            ["Preformatted 20-character stereo VU line."] = "Ligne VU stéréo préformatée de 20 caractères.",
            ["20-band ASCII spectrum."] = "Spectre ASCII 20 bandes.",
            ["Raw spectrum array."] = "Tableau brut du spectre.",
            ["Peak spectrum value."] = "Valeur de crête du spectre.",
            ["20-band spectrum using the eight custom VFD glyph levels."] = "Spectre 20 bandes utilisant les huit niveaux de glyphes VFD personnalisés.",
            ["True while snapshots are fresh."] = "True tant que les instantanés sont récents.",
            ["Age of the last snapshot."] = "Âge du dernier instantané.",
            ["Typical page"] = "Page type",
            ["Windows Media Player Legacy"] = "Windows Media Player Legacy",
            ["Windows Media Player Legacy telemetry comes from the native background COM plug-in over the LIS2ControlCenter.WmpLegacy named pipe. The plug-in is telemetry-only and never accesses LIS2 hardware."] = "La télémétrie Windows Media Player Legacy provient du plug-in COM natif en arrière-plan via le tube nommé LIS2ControlCenter.WmpLegacy. Le plug-in fournit uniquement de la télémétrie et n’accède jamais directement au matériel LIS2.",
            ["Current media track number."] = "Numéro de piste actuel du média.",
            ["Typical WMP Legacy page"] = "Page WMP Legacy type",
            ["VU and spectrum require the LIS2 Control Center visualization to be selected in Windows Media Player Legacy. Metadata and playback state continue to work through the background plug-in even when another visualization is selected."] = "Le VU et le spectre nécessitent que la visualisation « LIS2 Control Center » soit sélectionnée dans Windows Media Player Legacy. Les métadonnées et l’état de lecture continuent de fonctionner via le plug-in d’arrière-plan même si une autre visualisation est sélectionnée.",
            ["Left VU level from the active WMP Legacy visualization."] = "Niveau VU gauche provenant de la visualisation WMP Legacy active.",
            ["Right VU level from the active WMP Legacy visualization."] = "Niveau VU droit provenant de la visualisation WMP Legacy active.",
            ["Preformatted 20-character stereo VU line from the active visualization."] = "Ligne VU stéréo préformatée de 20 caractères provenant de la visualisation active.",
            ["20-band ASCII spectrum from the active visualization."] = "Spectre ASCII 20 bandes provenant de la visualisation active.",
            ["Raw 20-band spectrum array from the active visualization."] = "Tableau brut du spectre 20 bandes provenant de la visualisation active.",
            ["Peak value of the current 20-band spectrum."] = "Valeur de crête du spectre 20 bandes actuel.",
            ["True while the LIS2 WMP Legacy visualization is active and sending audio snapshots."] = "True tant que la visualisation LIS2 WMP Legacy est active et envoie des instantanés audio.",
            ["Age of the last WMP Legacy visualization snapshot."] = "Âge du dernier instantané de visualisation WMP Legacy.",

            ["Events are temporary priority overlays. While active they override normal page rotation; after expiry the scheduler returns to the normal page."] = "Les événements sont des superpositions temporaires prioritaires. Lorsqu’ils sont actifs, ils remplacent la rotation normale des pages ; après expiration, le planificateur revient à la page normale.",
            ["Line 1 / Line 2: event text."] = "Ligne 1 / Ligne 2 : texte de l’événement.",
            ["Priority: higher priority events win."] = "Priorité : les événements de priorité plus élevée l’emportent.",
            ["Duration: 1–3600 seconds."] = "Durée : 1–3600 secondes.",
            ["Expired events are removed automatically."] = "Les événements expirés sont supprimés automatiquement.",

            ["Hardware uses LibreHardwareMonitor and publishes CPU, GPU, memory, motherboard, storage, network and controller sensor values."] = "Matériel utilise LibreHardwareMonitor et publie les valeurs des capteurs CPU, GPU, mémoire, carte mère, stockage, réseau et contrôleurs.",
            ["Variable pattern"] = "Modèle de variable",
            ["Hardware and sensor names are normalized: non-alphanumeric characters become underscores. Exact variable names depend on the computer."] = "Les noms de matériel et de capteurs sont normalisés : les caractères non alphanumériques deviennent des tirets bas. Les noms exacts dépendent de l’ordinateur.",
            ["Units"] = "Unités",
            ["Temperature → C"] = "Température → C",
            ["Load → %"] = "Charge → %",
            ["Fan → RPM"] = "Ventilateur → RPM",
            ["Clock → MHz"] = "Fréquence → MHz",
            ["Voltage → V"] = "Tension → V",
            ["Power → W"] = "Puissance → W",
            ["Data → GB"] = "Données → GB",
            ["SmallData → MB"] = "Petites données → MB",
            ["Throughput → B/s"] = "Débit → B/s",
            ["Currently detected hardware variables"] = "Variables matérielles actuellement détectées",

            ["Fan Control configures the four LIS2 fan channels. Software safety limits are applied before output is sent."] = "Le contrôle des ventilateurs configure les quatre canaux LIS2. Les limites de sécurité logicielles sont appliquées avant l’envoi des sorties.",
            ["Modes"] = "Modes",
            ["Fixed: configured fixed output."] = "Fixe : sortie fixe configurée.",
            ["Curve: interpolates between temperature/output points."] = "Courbe : interpolation entre les points température/sortie.",
            ["Follow: converts the selected numeric sensor value directly to a percentage."] = "Suivre : convertit directement la valeur numérique du capteur sélectionné en pourcentage.",
            ["External: uses an externally supplied percentage."] = "Externe : utilise un pourcentage fourni de l’extérieur.",
            ["Off: outputs 0% only when Allow stop is enabled; otherwise minimum output is used."] = "Arrêt : produit 0 % uniquement si « Autoriser l’arrêt » est activé ; sinon la sortie minimale est utilisée.",
            ["Safety"] = "Sécurité",
            ["Minimum: lower non-zero limit."] = "Minimum : limite inférieure non nulle.",
            ["Maximum: upper limit."] = "Maximum : limite supérieure.",
            ["Fail-safe: used when a required sensor is missing or invalid."] = "Sécurité : valeur utilisée lorsqu’un capteur requis est absent ou invalide.",
            ["Hysteresis: suppresses small curve changes."] = "Hystérésis : supprime les petites variations de la courbe.",
            ["Allow stop: permits 0% and requires explicit confirmation."] = "Autoriser l’arrêt : permet 0 % et exige une confirmation explicite.",
            ["Safe minimum speed and reliable restart at 0% are physical properties and must be verified with the actual fan hardware."] = "La vitesse minimale sûre et le redémarrage fiable après 0 % sont des propriétés physiques qui doivent être vérifiées avec les ventilateurs réels.",

            ["Settings controls transport, COM port, appearance/language and Windows startup."] = "Paramètres gère le transport, le port COM, l’apparence/la langue et le démarrage avec Windows.",
            ["Transport"] = "Transport",
            ["Virtual: software-only emulator and recommended mode without hardware."] = "Virtuel : émulateur purement logiciel et mode recommandé sans matériel.",
            ["Serial: physical LIS2. A COM port is required."] = "Série : LIS2 physique. Un port COM est requis.",
            ["Known serial parameters: 19200 baud, 8 data bits, no parity, one stop bit."] = "Paramètres série connus : 19200 bauds, 8 bits de données, aucune parité, un bit d’arrêt.",
            ["Appearance"] = "Apparence",
            ["Theme can follow Windows or use Light/Dark. Language can follow the system or use English, German, French, Turkish or Russian."] = "Le thème peut suivre Windows ou utiliser Clair/Sombre. La langue peut suivre le système ou utiliser l’anglais, l’allemand, le français, le turc ou le russe.",
            ["Startup / tray"] = "Démarrage / zone de notification",
            ["Autostart is per-user. Closing the main window normally keeps the application alive in the tray."] = "Le démarrage automatique est propre à l’utilisateur. Fermer la fenêtre principale laisse normalement l’application active dans la zone de notification.",

            ["Diagnostics combines application state, source health, Virtual LIS2 state and decoded command history."] = "Diagnostics regroupe l’état de l’application, la santé des sources, l’état du LIS2 virtuel et l’historique des commandes décodées.",
            ["Virtual LIS2"] = "LIS2 virtuel",
            ["Shows both lines, brightness, four fan outputs, all eight glyphs, rejected-command count and the most recent protocol error."] = "Affiche les deux lignes, la luminosité, les quatre sorties ventilateur, les huit glyphes, le nombre de commandes rejetées et la dernière erreur de protocole.",
            ["Command history"] = "Historique des commandes",
            ["Shows up to the last 200 writes as hexadecimal bytes plus decoded command descriptions."] = "Affiche jusqu’aux 200 dernières écritures sous forme d’octets hexadécimaux avec leur description décodée.",
            ["Export"] = "Export",
            ["Export diagnostic report saves the current snapshot for bug reports and hardware-validation sessions."] = "L’export du rapport de diagnostic enregistre l’instantané actuel pour les rapports de bogue et les sessions de validation matérielle.",

            ["Home Assistant is the universal read-only integration layer. The app authenticates to the WebSocket API, loads the initial states and then receives live state_changed events."] = "Home Assistant est la couche d’intégration universelle en lecture seule. L’application s’authentifie auprès de l’API WebSocket, charge les états initiaux puis reçoit les événements state_changed en direct.",
            ["Connection"] = "Connexion",
            ["URL: absolute http:// or https:// Home Assistant base URL."] = "URL : URL de base Home Assistant absolue en http:// ou https://.",
            ["Token: long-lived Home Assistant access token."] = "Jeton : jeton d’accès Home Assistant longue durée.",
            ["Test connection: checks WebSocket greeting and authentication."] = "Tester la connexion : vérifie l’accueil WebSocket et l’authentification.",
            ["Save / reconnect: stores settings and restarts the HA source."] = "Enregistrer / reconnecter : enregistre les paramètres et redémarre la source HA.",
            ["Connection failures are retried automatically."] = "Les échecs de connexion sont réessayés automatiquement.",
            ["The four basic variable forms"] = "Les quatre formes de variable de base",
            ["Entity state. Example result: 21.7"] = "État de l’entité. Exemple : 21,7",
            ["unit_of_measurement. Example result: °C"] = "unit_of_measurement. Exemple : °C",
            ["friendly_name. Example result: Living room temperature"] = "friendly_name. Exemple : Température du salon",
            ["Any attribute exposed by the entity. Example result: temperature"] = "Tout attribut exposé par l’entité. Exemple : temperature",
            ["Attribute examples"] = "Exemples d’attributs",
            ["The exact attributes depend entirely on the Home Assistant integration. Select an entity in the HA browser to see every attribute currently exposed by that entity."] = "Les attributs exacts dépendent entièrement de l’intégration Home Assistant. Sélectionnez une entité dans le navigateur HA pour voir tous les attributs qu’elle expose actuellement.",
            ["Example: current media title, if the media_player exposes media_title."] = "Exemple : titre du média actuel si le media_player expose media_title.",
            ["Example: current media artist, if available."] = "Exemple : artiste actuel, s’il est disponible.",
            ["Example: a custom/integration-specific disk attribute named free."] = "Exemple : attribut de disque personnalisé ou spécifique à une intégration nommé free.",
            ["Example: an attribute named temperature, if that weather entity exposes it."] = "Exemple : attribut nommé temperature si cette entité météo l’expose.",
            ["These are syntax examples, not a promise that every HA installation has those exact entities or attributes."] = "Il s’agit d’exemples de syntaxe, pas d’une garantie que chaque installation HA possède exactement ces entités ou attributs.",
            ["Aliases"] = "Alias",
            ["Assign an alias in the HA browser when an entity ID is long or unstable. The same state, Unit, FriendlyName and attribute namespace is then available below the alias."] = "Attribuez un alias dans le navigateur HA lorsqu’un ID d’entité est long ou peu pratique. Le même état, Unit, FriendlyName et espace de noms d’attributs deviennent alors disponibles sous cet alias.",
            ["Formatting examples"] = "Exemples de formatage",
            ["Formatting operations are the same as on every page variable: fallback, number, percent, bytes, prefix, suffix, upper and lower."] = "Les opérations de formatage sont les mêmes pour toutes les variables : fallback, number, percent, bytes, prefix, suffix, upper et lower.",
            ["Visibility examples"] = "Exemples de visibilité",
            ["Use the Visibility Builder on Pages to select a live HA variable and operator instead of typing the expression manually."] = "Utilisez le générateur de visibilité dans Pages pour sélectionner une variable HA en direct et un opérateur au lieu de saisir l’expression manuellement.",
            ["unknown / unavailable"] = "unknown / unavailable",
            ["The template renderer treats null, unknown and unavailable as unavailable. This is why fallback is especially useful for HA values."] = "Le moteur de modèles traite null, unknown et unavailable comme indisponibles. C’est pourquoi fallback est particulièrement utile avec les valeurs HA.",
            ["Arrays and objects"] = "Tableaux et objets",
            ["Some integrations expose structured attributes such as lists or objects. LIS2 Control Center exposes them as compact JSON."] = "Certaines intégrations exposent des attributs structurés tels que des listes ou des objets. LIS2 Control Center les expose sous forme de JSON compact.",
            ["Example result: [1,2,3]"] = "Exemple : [1,2,3]",
            ["Example result: {\"temperature\":21,\"condition\":\"sunny\"}"] = "Exemple : {\"temperature\":21,\"condition\":\"sunny\"}",
            ["For a 20x2 VFD, structured JSON is usually too large to display directly. Use the HA browser to inspect it; dedicated extraction/formatting should only be added for a concrete real-world use case."] = "Pour un VFD 20x2, le JSON structuré est généralement trop volumineux pour être affiché directement. Inspectez-le dans le navigateur HA ; une extraction ou un formatage spécifique ne devrait être ajouté que pour un besoin réel concret.",
            ["How to find the exact variable"] = "Comment trouver la variable exacte",
            ["Open Home Assistant in LIS2 Control Center."] = "Ouvrez Home Assistant dans LIS2 Control Center.",
            ["Search by entity ID, friendly name or alias."] = "Recherchez par ID d’entité, nom convivial ou alias.",
            ["Select the entity."] = "Sélectionnez l’entité.",
            ["Use the attribute list to inspect every available attribute."] = "Utilisez la liste des attributs pour examiner tous les attributs disponibles.",
            ["Use Copy key or Create display page to avoid typing long keys manually."] = "Utilisez « Copier la clé » ou « Créer une page d’affichage » pour éviter de saisir manuellement de longues clés.",
            ["The help deliberately does not list every entity from your real Home Assistant instance. Large installations can have thousands of entities; the HA browser is the authoritative live catalogue."] = "L’aide ne liste volontairement pas toutes les entités de votre instance Home Assistant réelle. Les grandes installations peuvent en contenir des milliers ; le navigateur HA constitue le catalogue en direct de référence."
        };
}
