namespace LIS2.App;

internal static partial class HelpLocalization
{
    private static readonly IReadOnlyDictionary<string, string> German =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["LIS2 Control Center Help"] = "LIS2 Control Center Hilfe",
            ["Help & reference"] = "Hilfe & Referenz",
            ["Help for this page"] = "Hilfe zu dieser Seite",
            ["Instructions, configuration reference and display-variable examples."] = "Anleitungen, Konfigurationsreferenz und Beispiele für Anzeigevariablen.",

            ["The Dashboard is the operational overview. It shows the current 20x2 VFD frame, connection state, virtual-device state, recent log messages and direct fan-output controls."] = "Die Übersicht ist die zentrale Betriebsansicht. Sie zeigt den aktuellen 20x2-VFD-Inhalt, den Verbindungsstatus, den Zustand des virtuellen Geräts, die letzten Protokollmeldungen und die direkte Lüftersteuerung.",
            ["VFD Preview"] = "VFD-Vorschau",
            ["Shows the two normalized 20-character lines currently held by the application. Long page text may scroll at runtime; the preview shows the current rendered frame."] = "Zeigt die beiden auf 20 Zeichen normierten Zeilen, die die Anwendung aktuell ausgibt. Lange Seitentexte können während der Laufzeit scrollen; die Vorschau zeigt den momentan gerenderten Frame.",
            ["Fan Outputs"] = "Lüfterausgänge",
            ["The four sliders apply manual outputs through the same safety limits configured on Fan Control. Minimum and maximum limits still apply."] = "Die vier Schieberegler setzen manuelle Lüfterwerte unter Beachtung derselben Sicherheitsgrenzen wie in der Lüftersteuerung. Minimum und Maximum gelten weiterhin.",
            ["Quick links and status"] = "Schnellzugriffe und Status",
            ["Quick links open Display or Fan Control. With Virtual transport selected, the status card mirrors the emulated LIS2 state."] = "Die Schnellzugriffe öffnen Anzeige oder Lüftersteuerung. Bei ausgewähltem virtuellem Transport zeigt die Statuskarte den emulierten LIS2-Zustand.",

            ["Display contains direct low-level controls for the physical or virtual LIS2. They bypass page scheduling and are intended for testing and one-off output."] = "Anzeige enthält direkte Low-Level-Steuerungen für das physische oder virtuelle LIS2. Sie umgehen die Seitenrotation und sind für Tests oder einmalige Ausgaben gedacht.",
            ["Direct line output"] = "Direkte Zeilenausgabe",
            ["Line 1 and Line 2 are each limited to 20 display characters. Render both lines writes a complete frame. Clear sends the LIS2 clear/reset command."] = "Zeile 1 und Zeile 2 sind jeweils auf 20 Anzeigezeichen begrenzt. „Beide Zeilen anzeigen“ schreibt einen vollständigen Frame. „Leeren“ sendet den LIS2-Lösch-/Reset-Befehl.",
            ["Brightness"] = "Helligkeit",
            ["Supported levels are 100%, 75%, 50% and 25%. Brightness-off remains intentionally unsupported until verified on real hardware."] = "Unterstützt werden 100 %, 75 %, 50 % und 25 %. Helligkeit 0/Aus bleibt absichtlich deaktiviert, bis das Verhalten an echter Hardware verifiziert ist.",
            ["Custom characters / CG Builder"] = "Benutzerdefinierte Zeichen / CG Builder",
            ["The LIS2 exposes eight programmable 5x8 character slots. Use these variables in page templates:"] = "Das LIS2 stellt acht programmierbare 5x8-Zeichenslots bereit. Diese Variablen können in Seitenvorlagen verwendet werden:",
            ["Named glyphs use the saved glyph name after normalization."] = "Benannte Glyphen verwenden nach der Normalisierung den gespeicherten Glyphennamen.",
            ["Character ROM"] = "Zeichen-ROM",
            ["Special-character and raw-ROM tools are validation tools for the known uPD16314 mapping. Physical behavior still needs verification on the real LIS2."] = "Die Werkzeuge für Sonderzeichen und rohe ROM-Bytes dienen zur Prüfung der bekannten uPD16314-Zuordnung. Das physische Verhalten muss weiterhin am echten LIS2 verifiziert werden.",

            ["Pages define the rotating VFD presentation. Each enabled page has two templates, duration, optional visibility rules and an independent overflow mode per line."] = "Seiten definieren die rotierende VFD-Anzeige. Jede aktivierte Seite besitzt zwei Vorlagen, eine Dauer, optionale Sichtbarkeitsregeln und einen eigenen Überlaufmodus pro Zeile.",
            ["Configuration"] = "Konfiguration",
            ["Name: descriptive page name."] = "Name: beschreibender Seitenname.",
            ["Enabled: disabled pages are excluded from rotation."] = "Aktiviert: deaktivierte Seiten werden bei der Rotation übersprungen.",
            ["Duration: page lifetime in seconds; minimum 1 second."] = "Dauer: Anzeigedauer der Seite in Sekunden; mindestens 1 Sekunde.",
            ["Line 1 / Line 2: text templates with {Variable} placeholders."] = "Zeile 1 / Zeile 2: Textvorlagen mit {Variable}-Platzhaltern.",
            ["Overflow: PingPong, Marquee or Truncate per line."] = "Überlauf: PingPong, Laufschrift oder Abschneiden pro Zeile.",
            ["Scroll step: 50–5000 ms in the editor."] = "Scroll-Schritt: 50–5000 ms im Editor.",
            ["Edge pause: 0–10000 ms in the editor."] = "Randpause: 0–10000 ms im Editor.",
            ["Visible when: optional condition controlling whether the page is eligible."] = "Sichtbar wenn: optionale Bedingung, die bestimmt, ob die Seite angezeigt werden darf.",
            ["Template formatting"] = "Vorlagenformatierung",
            ["Operations can be chained left to right. fallback handles missing, null, unknown or unavailable values. number supports 0–6 decimals. bytes uses B/KB/MB/GB/TB/PB."] = "Operationen können von links nach rechts verkettet werden. fallback behandelt fehlende, null-, unknown- oder unavailable-Werte. number unterstützt 0–6 Nachkommastellen. bytes verwendet B/KB/MB/GB/TB/PB.",
            ["Visibility expressions"] = "Sichtbarkeitsausdrücke",
            ["Supported operators are =, !=, >, >=, < and <=. Equality is case-insensitive text comparison; ordering operators require numeric values."] = "Unterstützte Operatoren sind =, !=, >, >=, < und <=. Gleichheit vergleicht Text ohne Beachtung der Groß-/Kleinschreibung; Größenvergleiche benötigen numerische Werte.",
            ["Clock variables"] = "Uhr-Variablen",
            ["Current local time, HH:mm:ss."] = "Aktuelle lokale Uhrzeit im Format HH:mm:ss.",
            ["Current local date, dd.MM.yyyy."] = "Aktuelles lokales Datum im Format dd.MM.yyyy.",
            ["Current local weekday."] = "Aktueller lokaler Wochentag.",
            ["Currently available variables"] = "Aktuell verfügbare Variablen",
            ["This list comes from the current runtime snapshot. Home Assistant itself is intentionally not expanded into thousands of help entries; use the dedicated HA help with examples and the HA browser for exact entity/attribute names."] = "Diese Liste stammt aus dem aktuellen Laufzeit-Snapshot. Home Assistant wird absichtlich nicht in Tausende Hilfeeinträge aufgebläht; verwende die ausführliche HA-Hilfe mit Beispielen und den HA-Browser für exakte Entity- und Attributnamen.",
            ["No matching runtime variables are currently available."] = "Derzeit sind keine passenden Laufzeitvariablen verfügbar.",

            ["Winamp telemetry comes from the native x86 gen_lis2.dll plug-in over the LIS2ControlCenter.Winamp named pipe."] = "Die Winamp-Telemetrie kommt vom nativen x86-Plug-in gen_lis2.dll über die Named Pipe LIS2ControlCenter.Winamp.",
            ["All Winamp variables"] = "Alle Winamp-Variablen",
            ["Unknown, Stopped, Paused or Playing."] = "Unknown, Stopped, Paused oder Playing.",
            ["Current artist."] = "Aktueller Interpret.",
            ["Current title."] = "Aktueller Titel.",
            ["Current album."] = "Aktuelles Album.",
            ["Current playlist position."] = "Aktuelle Position in der Wiedergabeliste.",
            ["Number of playlist entries."] = "Anzahl der Einträge in der Wiedergabeliste.",
            ["Elapsed time as mm:ss."] = "Vergangene Zeit als mm:ss.",
            ["Track duration as mm:ss."] = "Titeldauer als mm:ss.",
            ["Bitrate in kbit/s."] = "Bitrate in kbit/s.",
            ["Sample rate in Hz."] = "Abtastrate in Hz.",
            ["Left VU level."] = "Linker VU-Pegel.",
            ["Right VU level."] = "Rechter VU-Pegel.",
            ["Preformatted 20-character stereo VU line."] = "Vorformatierte 20-Zeichen-Stereo-VU-Zeile.",
            ["20-band ASCII spectrum."] = "20-Band-ASCII-Spektrum.",
            ["Raw spectrum array."] = "Rohes Spektrum-Array.",
            ["Peak spectrum value."] = "Spitzenwert des Spektrums.",
            ["20-band spectrum using the eight custom VFD glyph levels."] = "20-Band-Spektrum mit den acht benutzerdefinierten VFD-Glyphenstufen.",
            ["True while snapshots are fresh."] = "True, solange aktuelle Snapshots eintreffen.",
            ["Age of the last snapshot."] = "Alter des letzten Snapshots.",
            ["Typical page"] = "Typische Seite",
            ["Windows Media Player Legacy"] = "Windows Media Player Legacy",
            ["Windows Media Player Legacy telemetry comes from the native background COM plug-in over the LIS2ControlCenter.WmpLegacy named pipe. The plug-in is telemetry-only and never accesses LIS2 hardware."] = "Die Windows-Media-Player-Legacy-Telemetrie kommt vom nativen COM-Hintergrund-Plug-in über die Named Pipe LIS2ControlCenter.WmpLegacy. Das Plug-in liefert ausschließlich Telemetrie und greift niemals direkt auf die LIS2-Hardware zu.",
            ["Current media track number."] = "Aktuelle Titelnummer des Mediums.",
            ["Typical WMP Legacy page"] = "Typische WMP-Legacy-Seite",

            ["Events are temporary priority overlays. While active they override normal page rotation; after expiry the scheduler returns to the normal page."] = "Ereignisse sind temporäre Einblendungen mit Priorität. Solange sie aktiv sind, überlagern sie die normale Seitenrotation; nach Ablauf kehrt der Scheduler zur normalen Seite zurück.",
            ["Line 1 / Line 2: event text."] = "Zeile 1 / Zeile 2: Ereignistext.",
            ["Priority: higher priority events win."] = "Priorität: Ereignisse mit höherer Priorität gewinnen.",
            ["Duration: 1–3600 seconds."] = "Dauer: 1–3600 Sekunden.",
            ["Expired events are removed automatically."] = "Abgelaufene Ereignisse werden automatisch entfernt.",

            ["Hardware uses LibreHardwareMonitor and publishes CPU, GPU, memory, motherboard, storage, network and controller sensor values."] = "Hardware verwendet LibreHardwareMonitor und stellt Sensorwerte für CPU, GPU, Arbeitsspeicher, Mainboard, Datenträger, Netzwerk und Controller bereit.",
            ["Variable pattern"] = "Variablenmuster",
            ["Hardware and sensor names are normalized: non-alphanumeric characters become underscores. Exact variable names depend on the computer."] = "Hardware- und Sensornamen werden normalisiert: Nicht alphanumerische Zeichen werden zu Unterstrichen. Die exakten Variablennamen hängen vom jeweiligen Computer ab.",
            ["Units"] = "Einheiten",
            ["Temperature → C"] = "Temperatur → C",
            ["Load → %"] = "Auslastung → %",
            ["Fan → RPM"] = "Lüfter → RPM",
            ["Clock → MHz"] = "Takt → MHz",
            ["Voltage → V"] = "Spannung → V",
            ["Power → W"] = "Leistung → W",
            ["Data → GB"] = "Daten → GB",
            ["SmallData → MB"] = "Kleine Datenmengen → MB",
            ["Throughput → B/s"] = "Durchsatz → B/s",
            ["Currently detected hardware variables"] = "Aktuell erkannte Hardware-Variablen",

            ["Fan Control configures the four LIS2 fan channels. Software safety limits are applied before output is sent."] = "Die Lüftersteuerung konfiguriert die vier LIS2-Lüfterkanäle. Softwareseitige Sicherheitsgrenzen werden angewendet, bevor Werte ausgegeben werden.",
            ["Modes"] = "Modi",
            ["Fixed: configured fixed output."] = "Fest: konfigurierter fester Ausgangswert.",
            ["Curve: interpolates between temperature/output points."] = "Kurve: interpoliert zwischen Temperatur-/Ausgabepunkten.",
            ["Follow: converts the selected numeric sensor value directly to a percentage."] = "Folgen: übernimmt den ausgewählten numerischen Sensorwert direkt als Prozentwert.",
            ["External: uses an externally supplied percentage."] = "Extern: verwendet einen extern gelieferten Prozentwert.",
            ["Off: outputs 0% only when Allow stop is enabled; otherwise minimum output is used."] = "Aus: gibt nur dann 0 % aus, wenn „Stopp erlauben“ aktiviert ist; andernfalls wird das Minimum verwendet.",
            ["Safety"] = "Sicherheit",
            ["Minimum: lower non-zero limit."] = "Minimum: untere Grenze für Werte größer als 0.",
            ["Maximum: upper limit."] = "Maximum: obere Grenze.",
            ["Fail-safe: used when a required sensor is missing or invalid."] = "Notfallwert: wird verwendet, wenn ein benötigter Sensor fehlt oder ungültig ist.",
            ["Hysteresis: suppresses small curve changes."] = "Hysterese: unterdrückt kleine Änderungen entlang der Kurve.",
            ["Allow stop: permits 0% and requires explicit confirmation."] = "Stopp erlauben: gestattet 0 % und erfordert eine ausdrückliche Bestätigung.",
            ["Safe minimum speed and reliable restart at 0% are physical properties and must be verified with the actual fan hardware."] = "Eine sichere Mindestdrehzahl und ein zuverlässiger Wiederanlauf nach 0 % sind physische Eigenschaften und müssen mit der echten Lüfterhardware geprüft werden.",

            ["Settings controls transport, COM port, appearance/language and Windows startup."] = "Einstellungen steuert Transport, COM-Port, Darstellung/Sprache und den Windows-Autostart.",
            ["Transport"] = "Transport",
            ["Virtual: software-only emulator and recommended mode without hardware."] = "Virtuell: reiner Software-Emulator und empfohlener Modus ohne Hardware.",
            ["Serial: physical LIS2. A COM port is required."] = "Seriell: physisches LIS2. Ein COM-Port ist erforderlich.",
            ["Known serial parameters: 19200 baud, 8 data bits, no parity, one stop bit."] = "Bekannte serielle Parameter: 19200 Baud, 8 Datenbits, keine Parität, ein Stoppbit.",
            ["Appearance"] = "Darstellung",
            ["Theme can follow Windows or use Light/Dark. Language can follow the system or use English, German, French, Turkish or Russian."] = "Das Design kann Windows folgen oder Hell/Dunkel verwenden. Die Sprache kann dem System folgen oder Englisch, Deutsch, Französisch, Türkisch oder Russisch sein.",
            ["Startup / tray"] = "Autostart / Infobereich",
            ["Autostart is per-user. Closing the main window normally keeps the application alive in the tray."] = "Der Autostart gilt pro Benutzer. Beim Schließen des Hauptfensters läuft die Anwendung normalerweise im Infobereich weiter.",

            ["Diagnostics combines application state, source health, Virtual LIS2 state and decoded command history."] = "Diagnose kombiniert Anwendungsstatus, Zustand der Datenquellen, virtuellen LIS2-Zustand und dekodierten Befehlsverlauf.",
            ["Virtual LIS2"] = "Virtuelles LIS2",
            ["Shows both lines, brightness, four fan outputs, all eight glyphs, rejected-command count and the most recent protocol error."] = "Zeigt beide Zeilen, Helligkeit, vier Lüfterausgänge, alle acht Glyphen, die Anzahl abgewiesener Befehle und den letzten Protokollfehler.",
            ["Command history"] = "Befehlsverlauf",
            ["Shows up to the last 200 writes as hexadecimal bytes plus decoded command descriptions."] = "Zeigt bis zu 200 letzte Schreibvorgänge als hexadezimale Bytes plus dekodierte Befehlsbeschreibung.",
            ["Export"] = "Export",
            ["Export diagnostic report saves the current snapshot for bug reports and hardware-validation sessions."] = "„Diagnosebericht exportieren“ speichert den aktuellen Snapshot für Fehlerberichte und Hardware-Validierung.",

            ["Home Assistant is the universal read-only integration layer. The app authenticates to the WebSocket API, loads the initial states and then receives live state_changed events."] = "Home Assistant ist die universelle, nur lesende Integrationsschicht. Die App authentifiziert sich an der WebSocket-API, lädt zunächst alle Zustände und empfängt danach live state_changed-Ereignisse.",
            ["Connection"] = "Verbindung",
            ["URL: absolute http:// or https:// Home Assistant base URL."] = "URL: absolute Home-Assistant-Basis-URL mit http:// oder https://.",
            ["Token: long-lived Home Assistant access token."] = "Token: langlebiges Home-Assistant-Zugriffstoken.",
            ["Test connection: checks WebSocket greeting and authentication."] = "Verbindung testen: prüft WebSocket-Begrüßung und Authentifizierung.",
            ["Save / reconnect: stores settings and restarts the HA source."] = "Speichern / neu verbinden: speichert die Einstellungen und startet die HA-Quelle neu.",
            ["Connection failures are retried automatically."] = "Verbindungsfehler werden automatisch erneut versucht.",
            ["The four basic variable forms"] = "Die vier grundlegenden Variablenformen",
            ["Entity state. Example result: 21.7"] = "Entity-Status. Beispielergebnis: 21,7",
            ["unit_of_measurement. Example result: °C"] = "unit_of_measurement. Beispielergebnis: °C",
            ["friendly_name. Example result: Living room temperature"] = "friendly_name. Beispielergebnis: Wohnzimmer Temperatur",
            ["Any attribute exposed by the entity. Example result: temperature"] = "Jedes von der Entity bereitgestellte Attribut. Beispielergebnis: temperature",
            ["Attribute examples"] = "Attribut-Beispiele",
            ["The exact attributes depend entirely on the Home Assistant integration. Select an entity in the HA browser to see every attribute currently exposed by that entity."] = "Die exakten Attribute hängen vollständig von der jeweiligen Home-Assistant-Integration ab. Wähle eine Entity im HA-Browser aus, um alle aktuell von dieser Entity bereitgestellten Attribute zu sehen.",
            ["Example: current media title, if the media_player exposes media_title."] = "Beispiel: aktueller Medientitel, sofern der media_player das Attribut media_title bereitstellt.",
            ["Example: current media artist, if available."] = "Beispiel: aktueller Interpret, sofern verfügbar.",
            ["Example: a custom/integration-specific disk attribute named free."] = "Beispiel: ein benutzerdefiniertes bzw. integrationsspezifisches Datenträgerattribut mit dem Namen free.",
            ["Example: an attribute named temperature, if that weather entity exposes it."] = "Beispiel: ein Attribut namens temperature, sofern diese Wetter-Entity es bereitstellt.",
            ["These are syntax examples, not a promise that every HA installation has those exact entities or attributes."] = "Dies sind Syntaxbeispiele und keine Zusage, dass jede HA-Installation exakt diese Entities oder Attribute besitzt.",
            ["Aliases"] = "Aliase",
            ["Assign an alias in the HA browser when an entity ID is long or unstable. The same state, Unit, FriendlyName and attribute namespace is then available below the alias."] = "Vergib im HA-Browser einen Alias, wenn eine Entity-ID lang oder unpraktisch ist. Status, Unit, FriendlyName und der gesamte Attribut-Namensraum stehen danach auch unter dem Alias zur Verfügung.",
            ["Formatting examples"] = "Formatierungsbeispiele",
            ["Formatting operations are the same as on every page variable: fallback, number, percent, bytes, prefix, suffix, upper and lower."] = "Die Formatierungsoperationen sind für alle Seitenvariablen gleich: fallback, number, percent, bytes, prefix, suffix, upper und lower.",
            ["Visibility examples"] = "Sichtbarkeitsbeispiele",
            ["Use the Visibility Builder on Pages to select a live HA variable and operator instead of typing the expression manually."] = "Verwende auf „Seiten“ den Sichtbarkeits-Builder, um eine Live-HA-Variable und einen Operator auszuwählen, statt den Ausdruck manuell einzugeben.",
            ["unknown / unavailable"] = "unknown / unavailable",
            ["The template renderer treats null, unknown and unavailable as unavailable. This is why fallback is especially useful for HA values."] = "Der Template-Renderer behandelt null, unknown und unavailable als nicht verfügbar. Deshalb ist fallback für HA-Werte besonders nützlich.",
            ["Arrays and objects"] = "Arrays und Objekte",
            ["Some integrations expose structured attributes such as lists or objects. LIS2 Control Center exposes them as compact JSON."] = "Einige Integrationen stellen strukturierte Attribute wie Listen oder Objekte bereit. LIS2 Control Center gibt sie als kompaktes JSON aus.",
            ["Example result: [1,2,3]"] = "Beispielergebnis: [1,2,3]",
            ["Example result: {\"temperature\":21,\"condition\":\"sunny\"}"] = "Beispielergebnis: {\"temperature\":21,\"condition\":\"sunny\"}",
            ["For a 20x2 VFD, structured JSON is usually too large to display directly. Use the HA browser to inspect it; dedicated extraction/formatting should only be added for a concrete real-world use case."] = "Für ein 20x2-VFD ist strukturiertes JSON meist zu groß für eine direkte Anzeige. Prüfe es im HA-Browser; eine spezielle Extraktion oder Formatierung sollte nur für einen konkreten Praxisfall ergänzt werden.",
            ["How to find the exact variable"] = "So findest du die exakte Variable",
            ["Open Home Assistant in LIS2 Control Center."] = "Öffne Home Assistant im LIS2 Control Center.",
            ["Search by entity ID, friendly name or alias."] = "Suche nach Entity-ID, Anzeigename oder Alias.",
            ["Select the entity."] = "Wähle die Entity aus.",
            ["Use the attribute list to inspect every available attribute."] = "Nutze die Attributliste, um alle verfügbaren Attribute zu prüfen.",
            ["Use Copy key or Create display page to avoid typing long keys manually."] = "Nutze „Schlüssel kopieren“ oder „Anzeigeseite erstellen“, um lange Schlüssel nicht manuell eingeben zu müssen.",
            ["The help deliberately does not list every entity from your real Home Assistant instance. Large installations can have thousands of entities; the HA browser is the authoritative live catalogue."] = "Die Hilfe listet bewusst nicht jede Entity deiner echten Home-Assistant-Instanz auf. Große Installationen können Tausende Entities besitzen; der HA-Browser ist der maßgebliche Live-Katalog."
        };
}
