namespace LIS2.App;

internal static partial class HelpLocalization
{
    private static readonly IReadOnlyDictionary<string, string> Turkish =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["LIS2 Control Center Help"] = "LIS2 Control Center Yardım",
            ["Help & reference"] = "Yardım ve başvuru",
            ["Help for this page"] = "Bu sayfa için yardım",
            ["Instructions, configuration reference and display-variable examples."] = "Talimatlar, yapılandırma başvurusu ve ekran değişkeni örnekleri.",

            ["The Dashboard is the operational overview. It shows the current 20x2 VFD frame, connection state, virtual-device state, recent log messages and direct fan-output controls."] = "Genel Bakış çalışma durumunun özetidir. Geçerli 20x2 VFD çerçevesini, bağlantı durumunu, sanal aygıt durumunu, son günlük iletilerini ve doğrudan fan çıkışı denetimlerini gösterir.",
            ["VFD Preview"] = "VFD Önizleme",
            ["Shows the two normalized 20-character lines currently held by the application. Long page text may scroll at runtime; the preview shows the current rendered frame."] = "Uygulamanın o anda tuttuğu 20 karaktere normalize edilmiş iki satırı gösterir. Uzun sayfa metinleri çalışma sırasında kayabilir; önizleme o anda oluşturulan çerçeveyi gösterir.",
            ["Fan Outputs"] = "Fan Çıkışları",
            ["The four sliders apply manual outputs through the same safety limits configured on Fan Control. Minimum and maximum limits still apply."] = "Dört kaydırıcı, Fan Denetimi’nde yapılandırılan aynı güvenlik sınırlarını kullanarak manuel çıkış uygular. Minimum ve maksimum sınırlar geçerliliğini korur.",
            ["Quick links and status"] = "Hızlı bağlantılar ve durum",
            ["Quick links open Display or Fan Control. With Virtual transport selected, the status card mirrors the emulated LIS2 state."] = "Hızlı bağlantılar Ekran veya Fan Denetimi’ni açar. Sanal aktarım seçildiğinde durum kartı öykünülen LIS2 durumunu yansıtır.",

            ["Display contains direct low-level controls for the physical or virtual LIS2. They bypass page scheduling and are intended for testing and one-off output."] = "Ekran, fiziksel veya sanal LIS2 için doğrudan düşük seviyeli denetimler içerir. Sayfa zamanlamasını atlar ve test ya da tek seferlik çıktı için kullanılır.",
            ["Direct line output"] = "Doğrudan satır çıkışı",
            ["Line 1 and Line 2 are each limited to 20 display characters. Render both lines writes a complete frame. Clear sends the LIS2 clear/reset command."] = "Satır 1 ve Satır 2 ayrı ayrı 20 ekran karakteriyle sınırlıdır. “Her iki satırı göster” tam bir çerçeve yazar. “Temizle” LIS2 temizleme/sıfırlama komutunu gönderir.",
            ["Brightness"] = "Parlaklık",
            ["Supported levels are 100%, 75%, 50% and 25%. Brightness-off remains intentionally unsupported until verified on real hardware."] = "Desteklenen seviyeler %100, %75, %50 ve %25’tir. Parlaklığı tamamen kapatma, gerçek donanımda doğrulanana kadar bilinçli olarak desteklenmez.",
            ["Custom characters / CG Builder"] = "Özel karakterler / CG Builder",
            ["The LIS2 exposes eight programmable 5x8 character slots. Use these variables in page templates:"] = "LIS2 sekiz adet programlanabilir 5x8 karakter yuvası sağlar. Sayfa şablonlarında şu değişkenleri kullanabilirsiniz:",
            ["Named glyphs use the saved glyph name after normalization."] = "Adlandırılmış glifler, normalizasyondan sonra kaydedilmiş glif adını kullanır.",
            ["Character ROM"] = "Karakter ROM’u",
            ["Special-character and raw-ROM tools are validation tools for the known uPD16314 mapping. Physical behavior still needs verification on the real LIS2."] = "Özel karakter ve ham ROM araçları bilinen uPD16314 eşlemesini doğrulamak içindir. Fiziksel davranışın gerçek LIS2 üzerinde ayrıca doğrulanması gerekir.",

            ["Pages define the rotating VFD presentation. Each enabled page has two templates, duration, optional visibility rules and an independent overflow mode per line."] = "Sayfalar dönen VFD sunumunu tanımlar. Etkin her sayfada iki şablon, süre, isteğe bağlı görünürlük kuralları ve her satır için bağımsız taşma modu bulunur.",
            ["Configuration"] = "Yapılandırma",
            ["Name: descriptive page name."] = "Ad: açıklayıcı sayfa adı.",
            ["Enabled: disabled pages are excluded from rotation."] = "Etkin: devre dışı sayfalar döngüye alınmaz.",
            ["Duration: page lifetime in seconds; minimum 1 second."] = "Süre: sayfanın saniye cinsinden gösterim süresi; en az 1 saniye.",
            ["Line 1 / Line 2: text templates with {Variable} placeholders."] = "Satır 1 / Satır 2: {Variable} yer tutucuları içeren metin şablonları.",
            ["Overflow: PingPong, Marquee or Truncate per line."] = "Taşma: her satır için PingPong, Marquee veya Truncate.",
            ["Scroll step: 50–5000 ms in the editor."] = "Kaydırma adımı: düzenleyicide 50–5000 ms.",
            ["Edge pause: 0–10000 ms in the editor."] = "Kenar beklemesi: düzenleyicide 0–10000 ms.",
            ["Visible when: optional condition controlling whether the page is eligible."] = "Şu durumda görünür: sayfanın gösterilip gösterilemeyeceğini belirleyen isteğe bağlı koşul.",
            ["Template formatting"] = "Şablon biçimlendirme",
            ["Operations can be chained left to right. fallback handles missing, null, unknown or unavailable values. number supports 0–6 decimals. bytes uses B/KB/MB/GB/TB/PB."] = "İşlemler soldan sağa zincirlenebilir. fallback eksik, null, unknown veya unavailable değerlerini işler. number 0–6 ondalık basamağı destekler. bytes B/KB/MB/GB/TB/PB kullanır.",
            ["Visibility expressions"] = "Görünürlük ifadeleri",
            ["Supported operators are =, !=, >, >=, < and <=. Equality is case-insensitive text comparison; ordering operators require numeric values."] = "Desteklenen işleçler =, !=, >, >=, < ve <=’dir. Eşitlik büyük/küçük harfe duyarsız metin karşılaştırması yapar; sıralama işleçleri sayısal değer gerektirir.",
            ["Clock variables"] = "Saat değişkenleri",
            ["Current local time, HH:mm:ss."] = "Geçerli yerel saat, HH:mm:ss.",
            ["Current local date, dd.MM.yyyy."] = "Geçerli yerel tarih, dd.MM.yyyy.",
            ["Current local weekday."] = "Geçerli yerel haftanın günü.",
            ["Currently available variables"] = "Şu anda kullanılabilir değişkenler",
            ["This list comes from the current runtime snapshot. Home Assistant itself is intentionally not expanded into thousands of help entries; use the dedicated HA help with examples and the HA browser for exact entity/attribute names."] = "Bu liste geçerli çalışma zamanı anlık görüntüsünden gelir. Home Assistant bilerek binlerce yardım girdisine genişletilmez; tam varlık/öznitelik adları için örnekli HA yardımını ve HA tarayıcısını kullanın.",
            ["No matching runtime variables are currently available."] = "Şu anda eşleşen çalışma zamanı değişkeni yok.",

            ["Winamp telemetry comes from the native x86 gen_lis2.dll plug-in over the LIS2ControlCenter.Winamp named pipe."] = "Winamp telemetrisi yerel x86 gen_lis2.dll eklentisinden LIS2ControlCenter.Winamp adlı kanal üzerinden gelir.",
            ["Windows Media Player"] = "Windows Media Player",
            ["Windows Media Player on Windows 11 is read directly from the Windows global media session (GSMTC). No player plug-in is required."] = "Windows 11 üzerindeki Windows Media Player, Windows genel medya oturumu (GSMTC) üzerinden doğrudan okunur. Oynatıcı eklentisi gerekmez.",
            ["All Windows Media variables"] = "Tüm Windows Media değişkenleri",
            ["Unknown, Closed, Opened, Changing, Stopped, Paused or Playing."] = "Unknown, Closed, Opened, Changing, Stopped, Paused veya Playing.",
            ["Current album artist."] = "Geçerli albüm sanatçısı.",
            ["Total tracks reported for the current album."] = "Geçerli albüm için bildirilen toplam parça sayısı.",
            ["Playback rate reported by Windows."] = "Windows tarafından bildirilen oynatma hızı.",
            ["Source application user model ID."] = "Kaynak uygulamanın kullanıcı modeli kimliği.",
            ["True while the Windows Media Player session is available."] = "Windows Media Player oturumu kullanılabilirken True.",
            ["Typical Windows Media page"] = "Tipik Windows Media sayfası",
            ["All Winamp variables"] = "Tüm Winamp değişkenleri",
            ["Unknown, Stopped, Paused or Playing."] = "Unknown, Stopped, Paused veya Playing.",
            ["Current artist."] = "Geçerli sanatçı.",
            ["Current title."] = "Geçerli parça adı.",
            ["Current album."] = "Geçerli albüm.",
            ["Current playlist position."] = "Çalma listesindeki geçerli konum.",
            ["Number of playlist entries."] = "Çalma listesi girdilerinin sayısı.",
            ["Elapsed time as mm:ss."] = "Geçen süre, mm:ss.",
            ["Track duration as mm:ss."] = "Parça süresi, mm:ss.",
            ["Bitrate in kbit/s."] = "Bit hızı, kbit/s.",
            ["Sample rate in Hz."] = "Örnekleme hızı, Hz.",
            ["Left VU level."] = "Sol VU seviyesi.",
            ["Right VU level."] = "Sağ VU seviyesi.",
            ["Preformatted 20-character stereo VU line."] = "Önceden biçimlendirilmiş 20 karakterlik stereo VU satırı.",
            ["20-band ASCII spectrum."] = "20 bant ASCII spektrumu.",
            ["Raw spectrum array."] = "Ham spektrum dizisi.",
            ["Peak spectrum value."] = "Spektrum tepe değeri.",
            ["20-band spectrum using the eight custom VFD glyph levels."] = "Sekiz özel VFD glif seviyesini kullanan 20 bant spektrumu.",
            ["True while snapshots are fresh."] = "Anlık görüntüler güncel olduğu sürece True.",
            ["Age of the last snapshot."] = "Son anlık görüntünün yaşı.",
            ["Typical page"] = "Tipik sayfa",
            ["Windows Media Player Legacy"] = "Windows Media Player Legacy",
            ["Windows Media Player Legacy telemetry comes from the native background COM plug-in over the LIS2ControlCenter.WmpLegacy named pipe. The plug-in is telemetry-only and never accesses LIS2 hardware."] = "Windows Media Player Legacy telemetrisi yerel arka plan COM eklentisinden LIS2ControlCenter.WmpLegacy adlı kanal üzerinden gelir. Eklenti yalnızca telemetri sağlar ve LIS2 donanımına hiçbir zaman doğrudan erişmez.",
            ["Current media track number."] = "Geçerli medyanın parça numarası.",
            ["Typical WMP Legacy page"] = "Tipik WMP Legacy sayfası",
            ["VU and spectrum require the LIS2 Control Center visualization to be selected in Windows Media Player Legacy. Metadata and playback state continue to work through the background plug-in even when another visualization is selected."] = "VU ve spektrum için Windows Media Player Legacy içinde “LIS2 Control Center” görselleştirmesinin seçili olması gerekir. Başka bir görselleştirme seçili olsa bile meta veriler ve oynatma durumu arka plan eklentisi üzerinden çalışmaya devam eder.",
            ["Left VU level from the active WMP Legacy visualization."] = "Etkin WMP Legacy görselleştirmesinden sol VU seviyesi.",
            ["Right VU level from the active WMP Legacy visualization."] = "Etkin WMP Legacy görselleştirmesinden sağ VU seviyesi.",
            ["Preformatted 20-character stereo VU line from the active visualization."] = "Etkin görselleştirmeden önceden biçimlendirilmiş 20 karakterlik stereo VU satırı.",
            ["20-band ASCII spectrum from the active visualization."] = "Etkin görselleştirmeden 20 bant ASCII spektrumu.",
            ["Raw 20-band spectrum array from the active visualization."] = "Etkin görselleştirmeden ham 20 bant spektrum dizisi.",
            ["Peak value of the current 20-band spectrum."] = "Geçerli 20 bant spektrumunun tepe değeri.",
            ["True while the LIS2 WMP Legacy visualization is active and sending audio snapshots."] = "LIS2 WMP Legacy görselleştirmesi etkin olup ses anlık görüntüleri gönderirken True.",
            ["Age of the last WMP Legacy visualization snapshot."] = "Son WMP Legacy görselleştirme anlık görüntüsünün yaşı.",

            ["Events are temporary priority overlays. While active they override normal page rotation; after expiry the scheduler returns to the normal page."] = "Olaylar geçici öncelikli kaplamalardır. Etkin olduklarında normal sayfa döngüsünü geçersiz kılar; süresi dolunca zamanlayıcı normal sayfaya döner.",
            ["Line 1 / Line 2: event text."] = "Satır 1 / Satır 2: olay metni.",
            ["Priority: higher priority events win."] = "Öncelik: daha yüksek öncelikli olaylar kazanır.",
            ["Duration: 1–3600 seconds."] = "Süre: 1–3600 saniye.",
            ["Expired events are removed automatically."] = "Süresi dolan olaylar otomatik kaldırılır.",

            ["Hardware uses LibreHardwareMonitor and publishes CPU, GPU, memory, motherboard, storage, network and controller sensor values."] = "Donanım, LibreHardwareMonitor kullanır ve CPU, GPU, bellek, anakart, depolama, ağ ve denetleyici sensör değerlerini yayımlar.",
            ["Variable pattern"] = "Değişken kalıbı",
            ["Hardware and sensor names are normalized: non-alphanumeric characters become underscores. Exact variable names depend on the computer."] = "Donanım ve sensör adları normalize edilir: alfasayısal olmayan karakterler alt çizgiye dönüşür. Kesin değişken adları bilgisayara bağlıdır.",
            ["Units"] = "Birimler",
            ["Temperature → C"] = "Sıcaklık → C",
            ["Load → %"] = "Yük → %",
            ["Fan → RPM"] = "Fan → RPM",
            ["Clock → MHz"] = "Saat → MHz",
            ["Voltage → V"] = "Gerilim → V",
            ["Power → W"] = "Güç → W",
            ["Data → GB"] = "Veri → GB",
            ["SmallData → MB"] = "Küçük veri → MB",
            ["Throughput → B/s"] = "Aktarım hızı → B/s",
            ["Currently detected hardware variables"] = "Şu anda algılanan donanım değişkenleri",

            ["Fan Control configures the four LIS2 fan channels. Software safety limits are applied before output is sent."] = "Fan Denetimi dört LIS2 fan kanalını yapılandırır. Çıkış gönderilmeden önce yazılım güvenlik sınırları uygulanır.",
            ["Modes"] = "Modlar",
            ["Fixed: configured fixed output."] = "Sabit: yapılandırılmış sabit çıkış.",
            ["Curve: interpolates between temperature/output points."] = "Eğri: sıcaklık/çıkış noktaları arasında interpolasyon yapar.",
            ["Follow: converts the selected numeric sensor value directly to a percentage."] = "Takip: seçilen sayısal sensör değerini doğrudan yüzdeye dönüştürür.",
            ["External: uses an externally supplied percentage."] = "Harici: dışarıdan sağlanan yüzde değerini kullanır.",
            ["Off: outputs 0% only when Allow stop is enabled; otherwise minimum output is used."] = "Kapalı: yalnızca Durdurmaya izin ver etkinse %0 verir; aksi halde minimum çıkış kullanılır.",
            ["Safety"] = "Güvenlik",
            ["Minimum: lower non-zero limit."] = "Minimum: sıfır olmayan alt sınır.",
            ["Maximum: upper limit."] = "Maksimum: üst sınır.",
            ["Fail-safe: used when a required sensor is missing or invalid."] = "Güvenli değer: gerekli sensör eksik veya geçersiz olduğunda kullanılır.",
            ["Hysteresis: suppresses small curve changes."] = "Histerezis: küçük eğri değişikliklerini bastırır.",
            ["Allow stop: permits 0% and requires explicit confirmation."] = "Durdurmaya izin ver: %0’a izin verir ve açık onay ister.",
            ["Safe minimum speed and reliable restart at 0% are physical properties and must be verified with the actual fan hardware."] = "Güvenli minimum hız ve %0’dan güvenilir yeniden başlama fiziksel özelliklerdir ve gerçek fan donanımıyla doğrulanmalıdır.",

            ["Settings controls transport, COM port, appearance/language and Windows startup."] = "Ayarlar; aktarımı, COM bağlantı noktasını, görünüm/dili ve Windows başlangıcını denetler.",
            ["Transport"] = "Aktarım",
            ["Virtual: software-only emulator and recommended mode without hardware."] = "Sanal: yalnızca yazılımsal öykünücü ve donanım yokken önerilen mod.",
            ["Serial: physical LIS2. A COM port is required."] = "Seri: fiziksel LIS2. Bir COM bağlantı noktası gerekir.",
            ["Known serial parameters: 19200 baud, 8 data bits, no parity, one stop bit."] = "Bilinen seri parametreler: 19200 baud, 8 veri biti, eşlik yok, bir dur biti.",
            ["Appearance"] = "Görünüm",
            ["Theme can follow Windows or use Light/Dark. Language can follow the system or use English, German, French, Turkish or Russian."] = "Tema Windows’u izleyebilir veya Açık/Koyu olabilir. Dil sistemi izleyebilir ya da İngilizce, Almanca, Fransızca, Türkçe veya Rusça kullanılabilir.",
            ["Startup / tray"] = "Başlangıç / bildirim alanı",
            ["Autostart is per-user. Closing the main window normally keeps the application alive in the tray."] = "Otomatik başlangıç kullanıcı bazındadır. Ana pencereyi kapatmak uygulamayı normalde bildirim alanında çalışır durumda tutar.",

            ["Diagnostics combines application state, source health, Virtual LIS2 state and decoded command history."] = "Tanılama; uygulama durumunu, kaynak sağlığını, Sanal LIS2 durumunu ve çözümlenmiş komut geçmişini bir araya getirir.",
            ["Virtual LIS2"] = "Sanal LIS2",
            ["Shows both lines, brightness, four fan outputs, all eight glyphs, rejected-command count and the most recent protocol error."] = "Her iki satırı, parlaklığı, dört fan çıkışını, sekiz glifi, reddedilen komut sayısını ve en son protokol hatasını gösterir.",
            ["Command history"] = "Komut geçmişi",
            ["Shows up to the last 200 writes as hexadecimal bytes plus decoded command descriptions."] = "Son 200 yazmaya kadar olan işlemleri onaltılık baytlar ve çözümlenmiş komut açıklamalarıyla gösterir.",
            ["Export"] = "Dışa aktar",
            ["Export diagnostic report saves the current snapshot for bug reports and hardware-validation sessions."] = "Tanılama raporunu dışa aktar, geçerli anlık görüntüyü hata raporları ve donanım doğrulama oturumları için kaydeder.",

            ["Home Assistant is the universal read-only integration layer. The app authenticates to the WebSocket API, loads the initial states and then receives live state_changed events."] = "Home Assistant evrensel salt okunur entegrasyon katmanıdır. Uygulama WebSocket API’sinde kimlik doğrular, başlangıç durumlarını yükler ve ardından canlı state_changed olaylarını alır.",
            ["Connection"] = "Bağlantı",
            ["URL: absolute http:// or https:// Home Assistant base URL."] = "URL: http:// veya https:// ile başlayan mutlak Home Assistant temel URL’si.",
            ["Token: long-lived Home Assistant access token."] = "Token: uzun ömürlü Home Assistant erişim belirteci.",
            ["Test connection: checks WebSocket greeting and authentication."] = "Bağlantıyı test et: WebSocket karşılama iletisini ve kimlik doğrulamayı denetler.",
            ["Save / reconnect: stores settings and restarts the HA source."] = "Kaydet / yeniden bağlan: ayarları kaydeder ve HA kaynağını yeniden başlatır.",
            ["Connection failures are retried automatically."] = "Bağlantı hataları otomatik olarak yeniden denenir.",
            ["The four basic variable forms"] = "Dört temel değişken biçimi",
            ["Entity state. Example result: 21.7"] = "Varlık durumu. Örnek sonuç: 21,7",
            ["unit_of_measurement. Example result: °C"] = "unit_of_measurement. Örnek sonuç: °C",
            ["friendly_name. Example result: Living room temperature"] = "friendly_name. Örnek sonuç: Oturma odası sıcaklığı",
            ["Any attribute exposed by the entity. Example result: temperature"] = "Varlığın sunduğu herhangi bir öznitelik. Örnek sonuç: temperature",
            ["Attribute examples"] = "Öznitelik örnekleri",
            ["The exact attributes depend entirely on the Home Assistant integration. Select an entity in the HA browser to see every attribute currently exposed by that entity."] = "Kesin öznitelikler tamamen Home Assistant entegrasyonuna bağlıdır. Bir varlığın o anda sunduğu tüm öznitelikleri görmek için HA tarayıcısında varlığı seçin.",
            ["Example: current media title, if the media_player exposes media_title."] = "Örnek: media_player media_title özniteliğini sunuyorsa geçerli medya başlığı.",
            ["Example: current media artist, if available."] = "Örnek: varsa geçerli sanatçı.",
            ["Example: a custom/integration-specific disk attribute named free."] = "Örnek: free adlı özel veya entegrasyona özgü disk özniteliği.",
            ["Example: an attribute named temperature, if that weather entity exposes it."] = "Örnek: hava durumu varlığı sunuyorsa temperature adlı öznitelik.",
            ["These are syntax examples, not a promise that every HA installation has those exact entities or attributes."] = "Bunlar sözdizimi örnekleridir; her HA kurulumunda bu varlıkların veya özniteliklerin aynısının bulunacağı anlamına gelmez.",
            ["Aliases"] = "Takma adlar",
            ["Assign an alias in the HA browser when an entity ID is long or unstable. The same state, Unit, FriendlyName and attribute namespace is then available below the alias."] = "Varlık kimliği uzun veya kullanışsızsa HA tarayıcısında bir takma ad verin. Aynı durum, Unit, FriendlyName ve öznitelik ad alanı daha sonra takma ad altında da kullanılabilir.",
            ["Formatting examples"] = "Biçimlendirme örnekleri",
            ["Formatting operations are the same as on every page variable: fallback, number, percent, bytes, prefix, suffix, upper and lower."] = "Biçimlendirme işlemleri tüm sayfa değişkenlerinde aynıdır: fallback, number, percent, bytes, prefix, suffix, upper ve lower.",
            ["Visibility examples"] = "Görünürlük örnekleri",
            ["Use the Visibility Builder on Pages to select a live HA variable and operator instead of typing the expression manually."] = "İfadeyi elle yazmak yerine Sayfalar’daki Görünürlük Oluşturucuyu kullanarak canlı bir HA değişkeni ve işleç seçin.",
            ["unknown / unavailable"] = "unknown / unavailable",
            ["The template renderer treats null, unknown and unavailable as unavailable. This is why fallback is especially useful for HA values."] = "Şablon oluşturucu null, unknown ve unavailable değerlerini kullanılamaz olarak değerlendirir. Bu nedenle fallback HA değerlerinde özellikle yararlıdır.",
            ["Arrays and objects"] = "Diziler ve nesneler",
            ["Some integrations expose structured attributes such as lists or objects. LIS2 Control Center exposes them as compact JSON."] = "Bazı entegrasyonlar listeler veya nesneler gibi yapılandırılmış öznitelikler sunar. LIS2 Control Center bunları kompakt JSON olarak sunar.",
            ["Example result: [1,2,3]"] = "Örnek sonuç: [1,2,3]",
            ["Example result: {\"temperature\":21,\"condition\":\"sunny\"}"] = "Örnek sonuç: {\"temperature\":21,\"condition\":\"sunny\"}",
            ["For a 20x2 VFD, structured JSON is usually too large to display directly. Use the HA browser to inspect it; dedicated extraction/formatting should only be added for a concrete real-world use case."] = "20x2 VFD için yapılandırılmış JSON genellikle doğrudan gösterilemeyecek kadar büyüktür. İncelemek için HA tarayıcısını kullanın; özel çıkarma/biçimlendirme yalnızca somut bir gerçek kullanım ihtiyacı olduğunda eklenmelidir.",
            ["How to find the exact variable"] = "Kesin değişken nasıl bulunur",
            ["Open Home Assistant in LIS2 Control Center."] = "LIS2 Control Center’da Home Assistant’ı açın.",
            ["Search by entity ID, friendly name or alias."] = "Varlık kimliği, görünen ad veya takma ada göre arayın.",
            ["Select the entity."] = "Varlığı seçin.",
            ["Use the attribute list to inspect every available attribute."] = "Kullanılabilir tüm öznitelikleri incelemek için öznitelik listesini kullanın.",
            ["Use Copy key or Create display page to avoid typing long keys manually."] = "Uzun anahtarları elle yazmamak için “Anahtarı kopyala” veya “Ekran sayfası oluştur” seçeneklerini kullanın.",
            ["The help deliberately does not list every entity from your real Home Assistant instance. Large installations can have thousands of entities; the HA browser is the authoritative live catalogue."] = "Yardım, gerçek Home Assistant örneğinizdeki her varlığı bilerek listelemez. Büyük kurulumlarda binlerce varlık olabilir; yetkili canlı katalog HA tarayıcısıdır."
        };
}
