<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>LIS2ControlCenter</AssemblyName>
    <RootNamespace>LIS2.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LIS2.Core\LIS2.Core.csproj" />
    <ProjectReference Include="..\LIS2.Display\LIS2.Display.csproj" />
    <ProjectReference Include="..\LIS2.Sources\LIS2.Sources.csproj" />
    <ProjectReference Include="..\LIS2.Fans\LIS2.Fans.csproj" />
    <ProjectReference Include="..\LIS2.Winamp\LIS2.Winamp.csproj" />
  </ItemGroup>
</Project>
